:hardbreaks:

= Modeling guide
:sectnums:

*Version:* 2.0

The purpose of this document is to provide the necessary information to model an electrical power grid according to the DIGIN10 model. 

The purpose of the DIGIN10 model is to equip the Norwegian power industry with a common tool for modeling the distribution network, in its entirety, in CGMES format.




// ////////////////////////////////////////////////////////////
:sectnums:
== General requirements
The Modeling guide is relevant for the following profiles:

--
//[no-bullet]
. Equipment Core (EQ)
. Equipment Operation (OP)
. Equipment Short Circuit (SC)
. Object Registry (OR)
. Steady State Hypothesis (SSH)
. Geographical Location (GL)
. Topology (TP) 
. Customer (CU)
. Diagram Layout (DL)
. State Variables (SV) 
. Medium Voltage 1 Low Voltage 1 Boundary Model (MV1-LV1_BM)
. High Voltage 1 Medium Voltage 1 Boundary Model (HV1-MV1_BM)
. Base Voltage Reference Data (BaseVoltage_RD)
. Geographical Region Reference Data (GeographicalRegion_RD)

--


=== Profile overview
An overview of the profiles and their respective classes can be found in the below Table:

--
[cols="1,1,1", width=100%]
[#tab:overview_profiles] 
|===
|*Equipment Core* |*Steady State Hypothesis*| *Geographical Location* 
1.7+<.<|  
    *LV1 and MV1:*
    ACLineSegment 
    Bay
    Breaker
    BusbarSection
    ConformLoad
    ConformLoadGroup
    ConnectivityNode
    CurrentLimit
    EquivalentInjection
    Line
    LoadArea
    OperationalLimitSet
    OperationalLimitType
    SubLoadArea
    Substation
    Terminal 
    Voltage level

    *MV1:*
    ControlArea
    Disconnector
    SynchronousMachine
    GeneratingUnit
    LinearShuntCompensator
    LoadBreakSwitch
    LoadResponseCharacteristic
    PetersenCoil
    PowerTransformer
    PowerTransformerEnd
    RatioTapChanger
    RegulatingControl
    TapChangerControl
// ------------------------------------------------------------
1.5+<.<|   *LV1:*
    ACLineSegment
    BusbarSection

    *LV1 and MV1:*
    Breaker
    ConformLoad
    CurrentLimit
    EquivalentInjection
    Terminal

    *MV1:*
    ControlArea
    Disconnector
    SynchronousMachine
    GeneratingUnit
    RegulatingControl
    LinearShuntCompensator
    LoadBreakSwitch
    RatioTapChanger
    RegulatingControl
// ------------------------------------------------------------
|   *LV1 and MV1:*
    CoordinateSystem
    Location
    PositionPoint   
// ------------------------------------------------------------ 
|   *Diagram Layout*
|   *LV1 and MV1:*
    Diagram

    *MV1:*
    DiagramObject
    DiagramObjectPoint
    DiagramObjectStyle
    TextDiagramObject 
// ------------------------------------------------------------ 
|*Customer*
|   *LV1:*
    UsagePoint  
// ------------------------------------------------------------     
// ------------------------------------------------------------     
|*State Variables*  |   *Topology*

// ------------------------------------------------------------ 
|   *MV1-LV1:*
    SvVoltage
    SvPowerFlow
    SvStatus
    SvTapStep
    SvShuntCompensatorSections

|   *MV1-LV1:*
    TopologicalIsland
    TopologicalNode
    ConnectivityNode
    Terminal
    pass:q[<br>]
// ------------------------------------------------------------ 
| *Equipment Operation* | *Equiment Short Circuit*| *Object Registry* 
|   -
|   -
|   *LV1:*
    Name
    NameType
    NameTypeAuthority 

| *Base Voltage Reference Data* | *Geographical Region Reference Data*| *Boundary Model* 
|   BasePower
    BaseVoltage

|   GeographicalRegion
    SubGeographicalRegion
|   *MV1-LV1:*
    Bay
    BoundaryPoint
    ConnectivityNode
    Substation
    VoltageLevel

    *HV1-MV1:*
    BoundaryPoint
    ConnectivityNode
    Substation
    VoltageLevel

|=== 
--





// ////////////////////////////////////////////////////////////
=== Data exchange format
The interested reader is referred to IEC 61970-600-1 (CGMES).


=== Units
CGMES 2.4.15 currently only supports fixed units for any given attribute. The following units have been used for the DIGIN10 model:
--
[grid=none, frame=none, width=30em]
|===
||
|Length|m
|Power|MW
|Reactive Power |MVAr
|Voltage |kV
|Current |A

|===
--

// ////////////////////////////////////////////////////////////

== Specific instructions
In addition to the previously presented profiles, the following sections describe how particular aspects should be modelled.

=== Boundary model
To support TSO-DSO-DSO-SGU model exchange there is a need to create the boundary models as bilateral boundary. In DIGIN10 we have created bilateral boundary models between HV1-MV1 and MV1-LV1. 

=== BusbarSection
It was decided that BusbarSection should be connected to a VoltageLevel when possible.

=== Breaker
All Breakers that are connected to the same ConnectivityNode must be connected to the same VoltageLevel.

=== ConformLoad
ConformLoad shall be connected via a Breaker to a Bay.


=== ConformLoadGroup
ConformLoadGroup is used as a container for loads. We have decided to use ConformLoadGroup for all ConformLoads below the same low voltage PowerTransformer.


=== ConnectivityNodes
ConnectiviyNodes belonging to BusbarSection would need to be contained by the VoltageLevel. All ConnectivityNode connected to a Switch (excpet if one of the ends are connected to a BusbarSection) shall be contained in the same Bay as the Switch.
Remaining ConnectivityNodes in a Substation should be connected to a VoltageLevel. All ConnectivityNode must be connected to a ConnectivityNodeContainer (Substation, VoltageLevel, Bay or Line).


=== ControlArea
The DIGIN10 model currently contains only one control area on the MV side. ControlArea will be adressed in coming releases.

=== Equipment containers
The DIGIN10 model uses the following equipent containers:

. Line
. Bay
. VoltageLevel
. Substation


=== EquivalentInjection
EquivalentInjection is included in the model, but switched off in cases where it is used to model a generator. This is because the tools that have been used to test the power flow does not support this function.

For such cases SynchronousMachine, its corresponding Terminal and a GeneratingUnit is added to emulate EquivalentInjection for the power flow. 

=== Feeder
Will be included in a later version of the DIGIN10 model.

=== Fuse
Will be included in a later version of the DIGIN10 model. In this version it is modelled as Breaker.

=== Line
Line.Region is optional. For the EQ profiles it is included in the MV files but excluded from the LV files.

=== LoadResponseCharacteristic
LoadResponseCharacteristic is included in the EQ profile for the MV grid to model large loads such as industrial loads.


=== ModelAuthoritySet
The CIM concept of Model Authority Sets is applied to enable the assembly and merging of model. It can also identify the source MAS when the merged model is referring to the original input model. Model Authority Sets allow an interconnection model to be divided into disjointed
sets of objects, which in turn allows different parties to take responsibility for different parts of a common grid model. 
Section 5.2 in IEC 61970-600-1:2021 gives the rules for handling of MAS.
In DIGIN we are using this to model HV, MV and LV separately, either by the fact that they are sourced by a different utility or application in the same organisation.


=== Object Registry
The Object Registry profile (part of ENTSO-E Network Code (NC) CGMES extensions (extension is also included in IEC 61968-100:2022) give the possibility to have multiple names for the same identifiable resource.

=== OperationalLimit
Only CurrentLimit is currently used and included as normalValue in the EQ files and value in the SSH files.

=== PowerTransformerEnd
PowerTransformerEnd.r and PowerTransformerEnd.x are defined on the primary winding of double winded transformers.

=== PATL and TATL
LV only includes Permanent Admissible Transmission Loading (PATL). The default limits are included in the EQ as e.g. CurrentLimit.normalValue. The result of the dynamic line rating is included in the SSH as e.g. CurrentLimit.value.


=== Reference Data
Common data for all MAS is included in Reference data files, BaseVoltage and GeograpicalRegion.

=== Substation
Substation is used to model cable cabinets in the LV files. This is an issue and might be changed in upcoming version.


=== Switch
Switch.locked is mandatory for CGMES 3.0 compliance and was added due to DisconnectingCircuitBreaker(DCB). In the DIGIN10 model the property is added for all switch types. However, the DCB breaker is not included in the current DIGIN10 model.

=== Terminal
If equipment is updated then the consolidated terminal must also be updated. If not, the Terminal cannot be used as it is simply embedded with the corresponding equipment and in reality is not equipment itself. 

include::..\docs\NameStandard.adoc[]






