:hardbreaks:

= Modelling guide
:sectnums:

The purpose of this document is to provide the necessary information to correctly model a network according to the DIGIN10 model. 

The purpose of the DIGIN10 model is to equip the Norwegian power industry with a common tool for modelling the distribution network, in its entirety, in CGMES format.

////
* Standard on which the document is based
* How work on the model is done
* How to navigate this document/Content overview
////


:sectnums!:
=== Project outline
Version 0.25 of the DIGIN10 model is based on GGMES 2.4.15 and aims to act as an example model to be used by power flow analysis tools. 

--
[grid=rows, frame=none, width=50%]
|===
|*Version* |*Coverage* | *Standard* | *Status*
|v.0.25 | MV grid       | CGMES 2.4.15 | In progress
|v.0.5  | MV + LV grid  | CGMES 2.4.15 | Planned
| ??    | MV + LV grid  | CGMES 2.5.?? | Planned
|===
--

// ////////////////////////////////////////////////////////////
:sectnums:
== General requirements
DIGIN10 v.0.25 contains the following profiles, all of which should be included to run a power flow analysis:

--
//[no-bullet]
. Equipment (EQ)
. Steady State Hypothesis (SSH)
. Geographical Location (GL)
. Diagram Layout (DL)
. _State Variables (SV )[red]#?#_
. Equipment Boundary (EQBP) model for the Nordic44 and DIGIN10 Test model
--


=== Profile overview
An overview of the profiles and their respective classes can be found in the below <<ModelingGuide.adoc#tab:overview_profiles, Table>>:

--
[cols="1,1,1", width=75%]
[#tab:overview_profiles] 
|===
|*Equipment* |*Steady State Hypothesis*| *Geographical Location* 
1.5+<.^|   
    ACLineSegment 
    Bay
    Breaker
    BusbarSection
    ConformLoad
    ConformLoadGroup
    ConnectivityNode
    ControlArea
    CurrentLimit
    Disconnector
    EquivalentInjection
    SynchronousMachine
    GeneratingUnit
    Line
    LinearShuntCompensator
    LoadArea
    LoadBreakSwitch
    LoadResponseCharacteristic
    OperationalLimitSet
    OperationalLimitType
    PetersenCoil
    PowerTransformer
    PowerTransformerEnd
    RatioTapChanger
    RegulatingControl
    SubGeographicalRegion
    SubLoadArea
    Substation
    TapChangerControl
    Terminal 
    Voltage level
// ------------------------------------------------------------
|   Breaker
    ConformLoad
    ControlArea
    Disconnector
    EquivalentInjection
    SynchronousMachine
    GeneratingUnit
    RegulatingControl
    LinearShuntCompensator
    LoadBreakSwitch
    RegulatingTapChanger
    TapChangerControl
    Terminal
// ------------------------------------------------------------
|   CoordinateSystem
    Location
    PositionPoint
// ------------------------------------------------------------ 
|   *Diagram Layout* | *State Variables*
|   Diagram
    DiagramObject
    DiagramObjectPoint
    DiagramObjectStyle
    TextDiagramObject
|   SvPowerFlow
    SvShuntCompensatorSections
    SvStatus
    SvTapStep
    TopologicalIsland
// ------------------------------------------------------------     
2.1+<.<|*Equipment Boundary profile*
2.1+<.<|   BasePower
    BaseVoltage
    GeographicalRegion
    SubGeographicalRegion
    EnergySchedulingType
    Substation
    VoltageLevel
    Bay
    ConnectivityNode


|=== 
--
// ////////////////////////////////////////////////////////////
=== [red]#Data exchange format#
Is this relevant/necessary? do we want to include something on this?


== Specific instructions
In addition to the previously presented profiles, the following sections describe how particular aspects should be modelled.

=== Equipment Boundary Profile
The boundary file is used to connect the DIGIN10 model to the Nordic44 model. In that way, vendors can connect the DIGIN10 model during testing of the Nordic44 model. 
The boundary profile is of importance in regards of shared equipment between different system operators and specifying information that remains equal on a global scale.

=== ConnectivityNodes
ConnectivityNodes shall be connected to a Bay through VoltageLevel to a Substation.
Not connecting ConnectivityNode to VoltageLevel directly provides more flexibility as it enables sorting of all nodes connected to a Bay.

=== Equipment containers
The DIGIN10 model uses the following equipent containers:

//_1f4fabd4-8c57-c245-b107-4e64c9007ae3

//_3d51330c-7528-4efb-8edc-e61dcc145ac4

//_681a21b6-5a55-11eb-a658-74e5f963e191

//_681a2179-5a55-11eb-a658-74e5f963e191

//_f1769670-9aeb-11e5-91da-b8763fd99c5f
. Line
. Bay
. VoltageLevel
. Substation
. ConformLoadGroup

=== EquivalentInjection
EquivalentInjection is included in the model, but switched off in cases where it is used to model a generator. This is because the tools that have been used to test the power flow does not support this function.

For such cases SynchronousMachine, its corresponding Terminal and a GeneratingUnit is added to emulate EquivalentInjection for the power flow. 



=== [red]#MasterAuthoritySet#

=== ConformLoad
ConformLoad shall be connected via a Breaker to a Bay.

Breaker is used instead of Fuse to ensure CGMES 2.4.15 conformity.


=== [red]#ConformLoadGroup#
ConformLoadGRoup is used as a container for loads.

=== BusbarSection
It was decided that BusbarSection should be connected to a VoltageLevel when possible.



=== Terminal
If equipment is updated then the consolidated terminal must also be updated. If not, the Terminal cannot be used as it is simply embedded with the corresponding equipment and in reality is not equipment itself. 







////
------------------------------ Should not be included--------------------------------
== Equipment model 

### ACLineSegment

cim:IdentifiedObject.aliasName 
//
cim:IdentifiedObject.description 
//
cim:IdentifiedObject.name 
//
cim:Equipment.aggregate 
//
cim:Conductor.length 
//
cim:ACLineSegment.b0ch 
//
cim:ACLineSegment.bch 
//
cim:ACLineSegment.g0ch 
//
cim:ACLineSegment.gch 
//
cim:ACLineSegment.r0 
//
cim:ACLineSegment.r 
//
cim:ACLineSegment.shortCircuitEndTemperature 
//
cim:ACLineSegment.x0 
//
cim:ACLineSegment.x 
//
cim:ConductingEquipment.BaseVoltage 
////



//// 

|===
|MV|LV

|cim:IdentifiedObject.aliasName 
//
cim:IdentifiedObject.description 
//
cim:IdentifiedObject.name 
//
cim:Equipment.aggregate 
//
cim:Conductor.length 
//
cim:ACLineSegment.b0ch 
//
cim:ACLineSegment.bch 
//
cim:ACLineSegment.g0ch 
//
cim:ACLineSegment.gch 
//
cim:ACLineSegment.r0 
//
cim:ACLineSegment.r 
//
cim:ACLineSegment.shortCircuitEndTemperature 
//
cim:ACLineSegment.x0 
//
cim:ACLineSegment.x 
//
cim:ConductingEquipment.BaseVoltage 
//
//
|cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:Equipment.aggregate
//
cim:Equipment.networkAnalysisEnabled
//
cim:Equipment.normallyInService
//
cim:Conductor.length
//
cim:ACLineSegment.b0ch
//
cim:ACLineSegment.bch
//
cim:ACLineSegment.g0ch
//
cim:ACLineSegment.gch
//
cim:ACLineSegment.r0
//
cim:ACLineSegment.r
//
cim:ACLineSegment.shortCircuitEndTemperature
//
cim:ACLineSegment.x0
//
cim:ACLineSegment.x
//
cim:PowerSystemResource.AssetDatasheet 
//
cim:ConductingEquipment.BaseVoltage 
|===

#### Bay
|===
|MV|LV

|cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Bay.VoltageLevel 
//
//
|cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName [red]#unused#
//
cim:Bay.VoltageLevel 
|===


#### Breaker
|===
|MV|LV

|
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.aggregate
//
cim:Equipment.EquipmentContainer 
//
cim:Switch.normalOpen
//
cim:Switch.ratedCurrent
//
cim:Switch.retained
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:Equipment.aggregate
//
cim:Equipment.networkAnalysisEnabled
//
cim:Equipment.normallyInService
//
cim:Switch.normalOpen
//
cim:Switch.ratedCurrent
//
cim:Switch.retained
//
cim:ProtectedSwitch.breakingCapacity
//
cim:Breaker.inTransitTime
//
cim:Equipment.EquipmentContainer 
//
cim:ConductingEquipment.BaseVoltage
//
|===


#### BusbarSection
|===
|MV|LV

|
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:BusbarSection.ipMax
//
cim:Equipment.EquipmentContainer 
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:Equipment.aggregate
//
cim:Equipment.networkAnalysisEnabled
//
cim:Equipment.normallyInService
//
cim:BusbarSection.ipMax
//
cim:Equipment.EquipmentContainer 
//
cim:ConductingEquipment.BaseVoltage 
//   
|===



#### ConformLoad
|===
|MV|LV

|
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:Equipment.EquipmentContainer 
//
cim:ConformLoad.LoadGroup 
//
cim:ConductingEquipment.BaseVoltage 
//
cim:Equipment.aggregate
//
cim:EnergyConsumer.LoadResponse 
//
cim:EnergyConsumer.pfixed
//
cim:EnergyConsumer.qfixed
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:Equipment.aggregate
//
cim:Equipment.networkAnalysisEnabled
//
cim:EnergyConsumer.customerCount
//
cim:EnergyConsumer.grounded
//
cim:EnergyConsumer.pfixed
//
cim:EnergyConsumer.pfixedPct
//
cim:EnergyConsumer.phaseConnection 
//
cim:EnergyConsumer.qfixed
//
cim:EnergyConsumer.qfixedPct
//
cim:PowerSystemResource.Location 
//
cim:Equipment.EquipmentContainer
//
cim:ConductingEquipment.BaseVoltage
//
cim:ConformLoad.LoadGroup 
//
|===

#### ConformLoadGroup
|===
|MV|LV

|
cim:LoadGroup.SubLoadArea 
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
//
|cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:LoadGroup.SubLoadArea 
//   
|===


#### ConnectivityNode
|===
|MV|LV

|
cim:IdentifiedObject.name
//
cim:ConnectivityNode.ConnectivityNodeContainer 
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:ConnectivityNode.ConnectivityNodeContainer 
//
|===

#### Control Area
|===
|MV

|
cim:IdentifiedObject.name
//
cim:ControlArea.type 
//
cim:ControlArea.EnergyArea
//
cim:IdentifiedObject.description
|===



#### CurrentLimit
|===
|MV|LV

|
cim:IdentifiedObject.name
//
cim:CurrentLimit.value
//
cim:OperationalLimit.OperationalLimitSet 
//
cim:OperationalLimit.OperationalLimitType 
//
//
|
cim:IdentifiedObject.name
//
cim:CurrentLimit.normalValue
//
cim:CurrentLimit.value
//
cim:OperationalLimit.OperationalLimitSet
//
cim:OperationalLimit.OperationalLimitType
//
|===



#### Disconnector
|===
|MV

|
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description>
//
cim:IdentifiedObject.name>
//
cim:Switch.normalOpen>
//
cim:Switch.ratedCurrent>
//
cim:Switch.retained
//
cim:Equipment.EquipmentContainer 
|===


#### EquivalentInjection
_Note that EquivalentInjection will be off [red]#[# ref regulationStatus?[red]#]# as it is not a part of the conformity assessment_

|===
|MV|LV

|
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:Equipment.aggregate
//
cim:EquivalentInjection.maxP
//
cim:EquivalentInjection.maxQ
//
cim:EquivalentInjection.minP
//
cim:EquivalentInjection.minQ
//
cim:EquivalentInjection.r
//
cim:EquivalentInjection.r0
//
cim:EquivalentInjection.r2
//
cim:EquivalentInjection.regulationCapability
//
cim:EquivalentInjection.x
//
cim:EquivalentInjection.x0
//
cim:EquivalentInjection.x2
//
cim:Equipment.EquipmentContainer 
//
cim:ConductingEquipment.BaseVoltage 
//
//
|
Same as for MV
|===


#### SynchronousMachine
_Added to emulate EquivalentInjection for the power flow_

|===
|MV

|
cim:SynchronousMachine.maxQ
//
cim:SynchronousMachine.maxU
//
cim:SynchronousMachine.minQ
//
cim:SynchronousMachine.minU
//
cim:SynchronousMachine.qPercent
//
cim:SynchronousMachine.r
//
cim:SynchronousMachine.type 
//
cim:RotatingMachine.GeneratingUnit 
//
cim:RotatingMachine.ratedS
//
cim:Equipment.EquipmentContainer 
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
|===

#### Terminal
[yellow]#added due to SynchronousMachine?#
cim:Terminal.ConductingEquipment 
//
cim:Terminal.ConnectivityNode 
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
//


#### GeneratingUnit
[yellow]#added due to SynchronousMachine?#

cim:GeneratingUnit.highControlLimit
//
cim:GeneratingUnit.initialP
//
cim:GeneratingUnit.lowControlLimit
//
cim:GeneratingUnit.maxEconomicP
//
cim:GeneratingUnit.maxOperatingP
//
cim:GeneratingUnit.minEconomicP
//
cim:GeneratingUnit.minOperatingP
//
cim:GeneratingUnit.nominalP
//
cim:GeneratingUnit.ratedGrossMaxP
//
cim:GeneratingUnit.ratedNetMaxP
//
cim:Equipment.EquipmentContainer 
//
cim:Equipment.aggregate
//
cim:Equipment.normallyInService
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name



#### RegulatingControl
cim:RegulatingControl.Terminal 
//
cim:RegulatingControl.mode 
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description



#### Fuse
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:Equipment.aggregate
//
cim:Equipment.networkAnalysisEnabled
//
cim:Equipment.normallyInService
//
cim:Switch.normalOpen
//
cim:Switch.ratedCurrent
//
cim:Switch.retained
//
cim:Equipment.EquipmentContainer 


	
#### Line
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:Line.Region 


	   
#### LinearShuntCompensator	
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.aggregate
//
cim:ShuntCompensator.aVRDelay
//
cim:ShuntCompensator.maximumSections
//
cim:ShuntCompensator.nomU
//
cim:ShuntCompensator.normalSections
//
cim:LinearShuntCompensator.b0PerSection
//
cim:LinearShuntCompensator.bPerSection
//
cim:LinearShuntCompensator.g0PerSection
//
cim:LinearShuntCompensator.gPerSection
//
cim:Equipment.EquipmentContainer 


#### LoadArea
|===
|MV|LV

|
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName [red]#unused#
//
|===



#### LoadBreakSwitch	
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.EquipmentContainer 
//
cim:ConductingEquipment.BaseVoltage
[red]#Optional? not used inn all objects# 
//
cim:Switch.normalOpen
//
cim:Switch.retained
//


#### LoadResponseCharacteristic
cim:LoadResponseCharacteristic.pConstantPower
//
cim:LoadResponseCharacteristic.qConstantPower
//
cim:LoadResponseCharacteristic.pVoltageExponent
//
cim:LoadResponseCharacteristic.pConstantCurrent
//
cim:LoadResponseCharacteristic.pConstantImpedance
//
cim:LoadResponseCharacteristic.qConstantCurrent
//
cim:LoadResponseCharacteristic.qConstantImpedance
//
cim:LoadResponseCharacteristic.exponentModel
//
cim:LoadResponseCharacteristic.qVoltageExponent
//
cim:LoadResponseCharacteristic.pFrequencyExponent
//
cim:LoadResponseCharacteristic.qFrequencyExponent
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description


#### Name
|===
|LV

|
cim:Name.name
cim:Name.IdentifiedObject 
cim:Name.NameType
//       
|===


#### NameType
|===
|LV

|
cim:NameType.description
cim:NameType.name
cim:NameType.NameTypeAthority
//
|===


#### NameTypeAuthority
|===
|LV

|
cim:NameTypeAuthority.description
//
cim:NameTypeAuthority.name
//
|===



#### OperationalLimitSet
|===
|MV|LV

|
cim:IdentifiedObject.name
//
cim:OperationalLimitSet.Terminal 
//
cim:OperationalLimitSet.Equipment 
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:OperationalLimitSet.Terminal
//
|===


#### OperationalLimitType
|===
|MV|LV

|
cim:IdentifiedObject.name
//
cim:OperationalLimitType.acceptableDuration
//
cim:OperationalLimitType.direction 
//
entsoe:OperationalLimitType.limitType 
//
cim:IdentifiedObject.description
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:OperationalLimitType.acceptableDuration
//
cim:OperationalLimitType.direction 
//
cim:OperationalLimitType.isInfiniteDuration
//
entsoe:OperationalLimitType.limitType 
//
|===   


#### PetersenCoil
|===
|MV
|
cim:IdentifiedObject.name
//
cim:Equipment.EquipmentContainer 
//
cim:IdentifiedObject.description
//
cim:Equipment.aggregate
[red]#Optional? not used inn all objects# 
//
|===


#### PowerTransformer
|===
|MV
|
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.EquipmentContainer 
//
cim:PowerTransformer.isPartOfGeneratorUnit
//
|===


#### PowerTransformerEnd
|===
|MV
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:TransformerEnd.endNumber
//
cim:TransformerEnd.grounded
//
cim:TransformerEnd.BaseVoltage 
//
cim:TransformerEnd.Terminal 
//
cim:PowerTransformerEnd.b0
//
cim:PowerTransformerEnd.b
//
cim:PowerTransformerEnd.connectionKind 
//
cim:PowerTransformerEnd.g
//
cim:PowerTransformerEnd.phaseAngleClock
//
cim:PowerTransformerEnd.r
//
cim:PowerTransformerEnd.r0
//
cim:PowerTransformerEnd.ratedS
//
cim:PowerTransformerEnd.ratedU
//
cim:PowerTransformerEnd.x
//
cim:PowerTransformerEnd.x0
//
cim:PowerTransformerEnd.PowerTransformer 
//
|===



#### RatioTapChanger
|===
|MV
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:TapChanger.highStep
//
cim:TapChanger.lowStep
//
cim:TapChanger.ltcFlag
//
cim:TapChanger.neutralStep
//
cim:TapChanger.neutralU
//
cim:TapChanger.normalStep
//
cim:RatioTapChanger.stepVoltageIncrement
//
cim:RatioTapChanger.tculControlMode 
//
cim:RatioTapChanger.TransformerEnd 
|===



#### RegulatingControl
|===
|MV
|
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:RegulatingControl.Terminal 
//
cim:RegulatingControl.mode 
//
|===


#### SubGeographicalRegion
|===
|LV
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:SubGeographicalRegion.Region
//
|===


#### SubLoadArea
|===
|MV|LV
|
cim:IdentifiedObject.name
//
cim:SubLoadArea.LoadArea 
//
cim:IdentifiedObject.description
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:SubLoadArea.LoadArea 
//
|===



#### Substation
|===
|MV|LV

|
cim:IdentifiedObject.name
//
cim:Substation.Region 
//
cim:IdentifiedObject.description
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:Substation.Region 
//
cim:PowerSystemResource.Location
//
|===


#### TapChangerControl
|===
|MV

|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:RegulatingControl.mode 
//
cim:RegulatingControl.Terminal 
//
|===

#### Terminal
|===
|MV|LV
|
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
[red]#Optional? not used inn all objects# 
//
cim:Terminal.ConnectivityNode 
//
cim:Terminal.ConductingEquipment 
//
cim:ACDCTerminal.sequenceNumber
//
cim:Terminal.phases
[red]#Optional? not used inn all objects# 
//
//
|
Same as for MV
|===




#### VoltageLevel
|===
|MV|LV

|
cim:IdentifiedObject.name
//
cim:VoltageLevel.BaseVoltage 
//
cim:VoltageLevel.Substation 
//
cim:IdentifiedObject.description
//
//
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:VoltageLevel.BaseVoltage 
//
cim:VoltageLevel.Substation
//
|===


#### UsagePoint
|===
|LV
|
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:UsagePoint.amiBillingReady 
//
cim:UsagePoint.chekBilling
//
cim:UsagePoint.connectionCategory
//
cim:UsagePoint.connectionState 
//
cim:UsagePoint.disconnectionMethod
//
cim:UsagePoint.estimatedLoad
//
cim:UsagePoint.grounded
//
cim:UsagePoint.isSdq
//
cim:UsagePoint.isVirtual
//
cim:UsagePoint.minimalUsageExpected
//
cim:UsagePoint.nominalServiceVoltage
//
cim:UsagePoint.outageRegion
//
cim:UsagePoint.phaseCode 
//
cim:UsagePoint.phaseCount
//
cim:UsagePoint.ratedCurrent
//
cim:UsagePoint.ratedPower
//
cim:UsagePoint.readCycle
//
cim:UsagePoint.readRoute
//
cim:UsagePoint.serviceDeliveryRemark
//
cim:UsagePoint.servicePriority
//
cim:UsagePoint.Equipments 


|===





## Steady State Hypothesis

### _MV_

#### Breaker
cim:Switch.open

#### ConformLoad
cim:EnergyConsumer.p
//
cim:EnergyConsumer.q


#### ControlArea
cim:ControlArea.netInterchange
//
cim:ControlArea.pTolerance


#### Disconnector
cim:Switch.open


#### EquivalentInjection
[red]#Will not be active#
//
cim:EquivalentInjection.p
//
cim:EquivalentInjection.q
//
cim:EquivalentInjection.regulationStatus
//
cim:EquivalentInjection.regulationTarget
//

#### SynchronousMachine
[red]#Added to emulate EquivalentInjection for the power flow#
//
cim:SynchronousMachine.operatingMode 
//
cim:SynchronousMachine.referencePriority
//
cim:RotatingMachine.p
//
cim:RotatingMachine.q
//
cim:RegulatingCondEq.controlEnabled
//
	

#### GeneratingUnit	
cim:GeneratingUnit.normalPF


#### RegulatingControl
cim:RegulatingControl.discrete
//
cim:RegulatingControl.enabled
//
cim:RegulatingControl.targetValue
//
cim:RegulatingControl.targetDeadband
//
cim:RegulatingControl.targetValueUnitMultiplier 


#### LinearShuntCompensator
cim:ShuntCompensator.sections
cim:RegulatingCondEq.controlEnabled
		

#### LoadBreakSwitch
cim:Switch.open


#### RatioTapChanger
cim:TapChanger.step
//
cim:TapChanger.controlEnabled


#### RegulatingControl
cim:RegulatingControl.discrete
//
cim:RegulatingControl.enabled
//
cim:RegulatingControl.targetDeadband
//
cim:RegulatingControl.targetValue
//
cim:RegulatingControl.targetValueUnitMultiplier 


#### TapChangerControl	
cim:RegulatingControl.discrete
//
cim:RegulatingControl.enabled
//
cim:RegulatingControl.targetDeadband
//
cim:RegulatingControl.targetValue
//
cim:RegulatingControl.targetValueUnitMultiplier 


#### Terminal
cim:ACDCTerminal.connected	


## Geographical Location
### _MV_


#### CoordinateSystem
cim:IdentifiedObject.name
//
cim:CoordinateSystem.crsUrn
    

#### Location
cim:Location.CoordinateSystem 
//
cim:Location.PowerSystemResources 
//
cim:IdentifiedObject.name
//


#### PositionPoint
cim:PositionPoint.sequenceNumber
//
cim:PositionPoint.xPosition
//
cim:PositionPoint.yPosition
//
cim:PositionPoint.Location 


## DiagramLayout
### _MV_

#### Diagram
<cim:IdentifiedObject.name
//
<cim:Diagram.orientation 
//
pti:Diagram.type
[red]#Optional?#


#### DiagramObject
cim:IdentifiedObject.name
//
cim:DiagramObject.Diagram 
//
cim:DiagramObject.IdentifiedObject 
//
cim:DiagramObject.DiagramObjectStyle 
//

#### DiagramObjectPoint
cim:DiagramObjectPoint.xPosition
//
cim:DiagramObjectPoint.yPosition
//
cim:DiagramObjectPoint.sequenceNumber
//
cim:DiagramObjectPoint.DiagramObject 
//
cim:DiagramObjectPoint.DiagramObjectGluePoint 
//


#### DiagramObjectStyle
cim:IdentifiedObject.name


#### TextDiagramObject
cim:IdentifiedObject.name
//
cim:DiagramObject.Diagram 
//
cim:TextDiagramObject.text
//
cim:DiagramObject.DiagramObjectStyle 
//



## State Variables
### _MV_

#### SvPowerFlow
cim:SvPowerFlow.Terminal 
//
cim:SvPowerFlow.p
//
cim:SvPowerFlow.q
//


#### SvShuntCompensatorSections
cim:SvShuntCompensatorSections.ShuntCompensator 
//
cim:SvShuntCompensatorSections.sections
//
 

#### SvStatus
cim:SvStatus.ConductingEquipment 
//
cim:SvStatus.inService
//
 

#### SvTapStep
cim:SvTapStep.TapChanger 
//
cim:SvTapStep.position
  

#### TopologicalIsland
[red]#Need to describe how this should be used? adding nodes etc?#
cim:TopologicalIsland.AngleRefTopologicalNode 
//
cim:IdentifiedObject.name
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 
//
cim:TopologicalIsland.TopologicalNodes 



## Equipment Boundary Profile

### BasePower
cim:IdentifiedObject.description
//
cim:BasePower.basePower
//


### BaseVoltage
[yellow]#Something about that objects should be added for both high voltage, medium voltage, low voltage and houshold voltage?#
//
cim:IdentifiedObject.description
//
cim:BaseVoltage.nominalVoltage
//
cim:IdentifiedObject.name
//
entsoe:IdentifiedObject.shortName


### GeographicalRegion
[yellow]#GeographicalRegion are defined as a Nordic to simplify and remove the contry domains.#
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
entsoe:IdentifiedObject.shortName
//


### SubGeographicalRegion
[yellow]#SubGeographicalRegion are defined as a Nordic to simplify and remove the contry domains.#
//
cim:SubGeographicalRegion.Region 
//
cim:IdentifiedObject.name
//
entsoe:IdentifiedObject.shortName
//
cim:IdentifiedObject.description
//


### EnergySchedulingType
[yellow]#These are the EnergySchedulingType that is needed for CGMES 3.0.#
//
<cim:IdentifiedObject.name
//
<cim:IdentifiedObject.description
//
<entsoe:IdentifiedObject.shortName
//



### Substation
[yellow]#Boundary points#
//
cim:IdentifiedObject.name
//
cim:Substation.Region 
//
cim:IdentifiedObject.description
//

### Substation
[yellow]#Boundary points to High voltage#
//
cim:Substation.Region 
//
cim:IdentifiedObject.name
//
pti:Substation.EnergySchedulingArea 
//

### VoltageLevel
[yellow]#Boundary points, also need boundary points to High voltage#
//
cim:IdentifiedObject.description
[red]#Optional? not included in boundary to HV#
//
cim:IdentifiedObject.name
//
cim:VoltageLevel.BaseVoltage 
//
cim:VoltageLevel.Substation 
//


### Bay
[yellow]#Boundary points#
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Bay.VoltageLevel 


### ConnectivityNode
[yellow]#Boundary points, also need boundary points to High voltage#
//
cim:IdentifiedObject.name
//
entsoe:IdentifiedObject.shortName
//
entsoe:ConnectivityNode.boundaryPoint
//
entsoe:ConnectivityNode.fromEndIsoCode
//
entsoe:ConnectivityNode.fromEndName
//
entsoe:ConnectivityNode.fromEndNameTso
//
entsoe:ConnectivityNode.toEndIsoCode
//
entsoe:ConnectivityNode.toEndName
//
entsoe:ConnectivityNode.toEndNameTso
//
cim:ConnectivityNode.ConnectivityNodeContainer 
//
cim:IdentifiedObject.description
[red]#Optional? only included in boundary to HV#
		
////

