:hardbreaks:

= Modeling guide
:sectnums:

*Version:* 1.0

The purpose of this document is to provide the necessary information to model a network according to the DIGIN10 model. 

The purpose of the DIGIN10 model is to equip the Norwegian power industry with a common tool for modeling the distribution network, in its entirety, in CGMES format.




// ////////////////////////////////////////////////////////////
:sectnums:
== General requirements
The Modeling guide is relevant for the following profiles:

--
//[no-bullet]
. Equipment (EQ)
. Steady State Hypothesis (SSH)
. Geographical Location (GL)
. Topology (TP) 
. Customer (CU)
. Diagram Layout (DL)
. State Variables (SV) 
. Equipment Boundary (EQBP)
. Topology Boundary (TPBP)

--


=== Profile overview
An overview of the profiles and their respective classes can be found in the below <<ModelingGuide.adoc#tab:overview_profiles, Table>>:

--
[cols="1,1,1", width=75%]
[#tab:overview_profiles] 
|===
|*Equipment* |*Steady State Hypothesis*| *Geographical Location* 
1.9+<.<|  *LV1:*
    Name
    NameType
    NameType Authority
    UsagePoint

    *LV1 and MV1:*
    ACLineSegment 
    Bay
    Breaker
    BusbarSection
    ConformLoad
    ConformLoadGroup
    ConnectivityNode
    CurrentLimit
    EquivalentInjection
    LoadArea
    OperationalLimitSet
    OperationalLimitType
    SubGeographicalRegion
    SubLoadArea
    Substation
    Terminal 
    Voltage level

    *MV1:*
    ControlArea
    Disconnector
    SynchronousMachine
    GeneratingUnit
    Line
    LinearShuntCompensator
    LoadBreakSwitch
    LoadResponseCharacteristic
    PetersenCoil
    PowerTransformer
    PowerTransformerEnd
    RatioTapChanger
    RegulatingControl
    TapChangerControl
// ------------------------------------------------------------
1.5+<.<|   *LV1:*
    ACLineSegment
    BusbarSection

    *LV1 and MV1:*
    Breaker
    ConformLoad
    Terminal

    *MV1:*
    ControlArea
    Disconnector
    EquivalentInjection
    SynchronousMachine
    GeneratingUnit
    RegulatingControl
    LinearShuntCompensator
    LoadBreakSwitch
    RegulatingTapChanger
    TapChangerControl
    
// ------------------------------------------------------------
|   *LV1 and MV1:*
    CoordinateSystem
    Location
    PositionPoint 
    pass:q[<br>]
    
// ------------------------------------------------------------ 
|*Topology*
|   *MV1-LV1:*
    TopologicalIsland
    TopologicalNode
    ConnectivityNode
    Terminal
    pass:q[<br>]
    

// ------------------------------------------------------------ 
|*Customer*
|   *LV1:*
    UsagePoint  
    pass:q[<br>]
    

// ------------------------------------------------------------     
// ------------------------------------------------------------     
|*Diagram Layout*  |   *Equipment Boundary*

// ------------------------------------------------------------ 
|   *LV1 and MV1:*
    Diagram

    *MV1:*
    DiagramObject
    DiagramObjectPoint
    DiagramObjectStyle
    TextDiagramObject

|   BasePower
    BaseVoltage
    GeographicalRegion
    SubGeographicalRegion
    EnergySchedulingType
    Substation
    VoltageLevel
    Bay
    ConnectivityNode

| *State Variables* | *Topology Boundary*
|   *MV1-LV1:*
    SvVoltage
    SvPowerFlow
    SvStatus
    SvTapStep
    SvShuntCompensatorSections

|   ConnectivityNode
    TopologicalNode

|=== 
--





// ////////////////////////////////////////////////////////////
=== Data exchange format
The interested reader is referred to IEC 61970-600-1 (CGMES).


=== Units
CGMES 2.4.15 currently only supports fixed units for any given attribute. The following units have been used for the DIGIN10 model:
--
[grid=none, frame=none, width=30em]
|===
||
|Length|m
|Power|MW
|Reactive Power |MVAr
|Voltage |kV
|Current |A

|===
--

// ////////////////////////////////////////////////////////////

== Specific instructions
In addition to the previously presented profiles, the following sections describe how particular aspects should be modelled.

=== BusbarSection
It was decided that BusbarSection should be connected to a VoltageLevel when possible.

=== Breaker
All Breakers that are connected to the same ConnectivityNode must be connected to the same VoltageLevel.

=== ConformLoad
ConformLoad shall be connected via a Breaker to a Bay.

Breaker is used instead of Fuse to ensure CGMES 2.4.15 conformity.


=== ConformLoadGroup
ConformLoadGroup is used as a container for loads. We have decided to use ConformLoadGroup for all ConformLoads below the same low voltage PowerTransformer.


=== ConnectivityNodes
ConnectiviyNodes belonging to BusbarSection would need to be contained by the VoltageLevel. All ConnectivityNode connected to a Switch (excpet if one of the ends are connected to a BusbarSection) shall be contained in the same Bay as the Switch.
Remaining ConnectivityNodes in a Substation should be connected to a VoltageLevel. All ConnectivityNode must be connected to a ConnectivityNodeContainer (Substation, VoltageLevel, Bay or Line).

=== Equipment Boundary Profile
The boundary file is used to connect the DIGIN10 model to the Nordic44 model. In that way, vendors can connect the DIGIN10 model during testing of the Nordic44 model. 
The boundary profile is of importance in regards of shared equipment between different system operators and specifying information that remains equal on a global scale.

=== Equipment containers
The DIGIN10 model uses the following equipent containers:

. Line
. Bay
. VoltageLevel
. Substation


=== EquivalentInjection
EquivalentInjection is included in the model, but switched off in cases where it is used to model a generator. This is because the tools that have been used to test the power flow does not support this function.

For such cases SynchronousMachine, its corresponding Terminal and a GeneratingUnit is added to emulate EquivalentInjection for the power flow. 



=== ModelAuthoritySet
The CIM concept of Model Authority Sets is applied to enable the assembly and merging of model. It can also identify the source MAS when the merged model is referring to the original input model. Model Authority Sets allow an interconnection model to be divided into disjointed
sets of objects, which in turn allows different parties to take responsibility for different parts of a common grid model. 
Section 5.2 in IEC 61970-600-1:2021 gives the rules for handling of MAS.
In DIGIN we are using this to model HV, MV and LV sepretaly, either by the fact that they are sourced by a different utility or application in the same organisation.

=== OperationalLimit
Only CurrentLimit is currently used and included as normalValue in the EQ files and value in the SSH files.

=== PowerTransformerEnd
PowerTransformerEnd.r and PowerTransformerEnd.x are defined on the primary winding of double wound transformers.

=== PATL and TATL
It was decided that this would be modelled in the EQ files by CurrentLimit.normalValue. 

=== Substation
Substation is used to model cable cabinets in the LV files in CIM16, this is subject to change in CIM17.

=== Terminal
If equipment is updated then the consolidated terminal must also be updated. If not, the Terminal cannot be used as it is simply embedded with the corresponding equipment and in reality is not equipment itself. 

include::..\docs\NameStandard.adoc[]






