:hardbreaks:
<style>
.indent {
    padding-left: 4rem;
}
</style>
= Modeling guide

_[yellow]#This document contains documentation of all profiles necessary to perform power flow analyses. .....#_
The set of profiles consists of Equipment (EQ), Steady State Hypothesis (SSH), Geographical Location (GL), Diagram Layout (DL) and _State Variables (SV )[red]#?#_, together with the Equipment Boundary (EQBP) model for the Nordic44 and DIGIN10 Test model.

## Equipment model 
### _MV_
#### ACLineSegment

cim:IdentifiedObject.aliasName 
//
cim:IdentifiedObject.description 
//
cim:IdentifiedObject.name 
//
cim:Equipment.aggregate 
//
cim:Conductor.length 
//
cim:ACLineSegment.b0ch 
//
cim:ACLineSegment.bch 
//
cim:ACLineSegment.g0ch 
//
cim:ACLineSegment.gch 
//
cim:ACLineSegment.r0 
//
cim:ACLineSegment.r 
//
cim:ACLineSegment.shortCircuitEndTemperature 
//
cim:ACLineSegment.x0 
//
cim:ACLineSegment.x 
//
cim:ConductingEquipment.BaseVoltage 



#### Bay
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Bay.VoltageLevel 


#### Breaker
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.aggregate
//
cim:Equipment.EquipmentContainer 
//
cim:Switch.normalOpen
//
cim:Switch.ratedCurrent
//
cim:Switch.retained


#### BusbarSection
cim:IdentifiedObject.aliasName>
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:BusbarSection.ipMax
//
cim:Equipment.EquipmentContainer 


#### ConformLoad
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:Equipment.EquipmentContainer 
//
cim:ConformLoad.LoadGroup 
//
cim:ConductingEquipment.BaseVoltage 
//
cim:Equipment.aggregate
//
cim:EnergyConsumer.LoadResponse 
//
cim:EnergyConsumer.pfixed
//
cim:EnergyConsumer.qfixed
//

#### ConformLoadGroup
cim:LoadGroup.SubLoadArea 
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description

#### ConnectivityNode
cim:IdentifiedObject.name
//
cim:ConnectivityNode.ConnectivityNodeContainer 

#### Control Area
cim:IdentifiedObject.name
//
cim:ControlArea.type 
//
cim:ControlArea.EnergyArea
//
cim:IdentifiedObject.description

#### CurrentLimit
cim:IdentifiedObject.name
//
cim:CurrentLimit.value
//
cim:OperationalLimit.OperationalLimitSet 
//
cim:OperationalLimit.OperationalLimitType 

#### Disconnector
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description>
//
cim:IdentifiedObject.name>
//
cim:Switch.normalOpen>
//
cim:Switch.ratedCurrent>
//
cim:Switch.retained
//
cim:Equipment.EquipmentContainer 

#### EquivalentInjection
_Note that EquivalentInjection will be off [red]#[# ref regulationStatus?[red]#]# as it is not a part of the conformity assessment_

cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:Equipment.aggregate
//
cim:EquivalentInjection.maxP
//
cim:EquivalentInjection.maxQ
//
cim:EquivalentInjection.minP
//
cim:EquivalentInjection.minQ
//
cim:EquivalentInjection.r
//
cim:EquivalentInjection.r0
//
cim:EquivalentInjection.r2
//
cim:EquivalentInjection.regulationCapability
//
cim:EquivalentInjection.x
//
cim:EquivalentInjection.x0
//
cim:EquivalentInjection.x2
//
cim:Equipment.EquipmentContainer 
//
cim:ConductingEquipment.BaseVoltage 


#### SynchronousMachine
_Added to emulate EquivalentInjection for the power flow_

cim:SynchronousMachine.maxQ
//
cim:SynchronousMachine.maxU
//
cim:SynchronousMachine.minQ
//
cim:SynchronousMachine.minU
//
cim:SynchronousMachine.qPercent
//
cim:SynchronousMachine.r
//
cim:SynchronousMachine.type [red]#is this a typo or should it be lower case (it is linked as rdf:resouce)#
//
cim:RotatingMachine.GeneratingUnit 
//
cim:RotatingMachine.ratedS
//
cim:Equipment.EquipmentContainer 
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name


#### Terminal
cim:Terminal.ConductingEquipment 
//
cim:Terminal.ConnectivityNode 
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description


#### GeneratingUnit
cim:GeneratingUnit.highControlLimit
//
cim:GeneratingUnit.initialP
//
cim:GeneratingUnit.lowControlLimit
//
cim:GeneratingUnit.maxEconomicP
//
cim:GeneratingUnit.maxOperatingP
//
cim:GeneratingUnit.minEconomicP
//
cim:GeneratingUnit.minOperatingP
//
cim:GeneratingUnit.nominalP
//
cim:GeneratingUnit.ratedGrossMaxP
//
cim:GeneratingUnit.ratedNetMaxP
//
cim:Equipment.EquipmentContainer 
//
cim:Equipment.aggregate
//
cim:Equipment.normallyInService
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name

#### RegulatingControl
cim:RegulatingControl.Terminal 
//
cim:RegulatingControl.mode [red]#is this a typo or should it be lower case (it is linked as rdf:resouce)#
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description

#### Fuse
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.aliasName
//
cim:Equipment.aggregate
//
cim:Equipment.networkAnalysisEnabled
//
cim:Equipment.normallyInService
//
cim:Switch.normalOpen
//
cim:Switch.ratedCurrent
//
cim:Switch.retained
//
cim:Equipment.EquipmentContainer 
	
#### Line
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:Line.Region 
	   
#### LinearShuntCompensator	
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.aggregate
//
cim:ShuntCompensator.aVRDelay
//
cim:ShuntCompensator.maximumSections
//
cim:ShuntCompensator.nomU
//
cim:ShuntCompensator.normalSections
//
cim:LinearShuntCompensator.b0PerSection
//
cim:LinearShuntCompensator.bPerSection
//
cim:LinearShuntCompensator.g0PerSection
//
cim:LinearShuntCompensator.gPerSection
//
cim:Equipment.EquipmentContainer 


#### LoadArea
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description


#### LoadBreakSwitch	
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.EquipmentContainer 
//
cim:ConductingEquipment.BaseVoltage
[red]#Optional? not used inn all objects# 
//
cim:Switch.normalOpen
//
cim:Switch.retained
//


#### LoadResponseCharacteristic
cim:LoadResponseCharacteristic.pConstantPower
//
cim:LoadResponseCharacteristic.qConstantPower
//
cim:LoadResponseCharacteristic.pVoltageExponent
//
cim:LoadResponseCharacteristic.pConstantCurrent
//
cim:LoadResponseCharacteristic.pConstantImpedance
//
cim:LoadResponseCharacteristic.qConstantCurrent
//
cim:LoadResponseCharacteristic.qConstantImpedance
//
cim:LoadResponseCharacteristic.exponentModel
//
cim:LoadResponseCharacteristic.qVoltageExponent
//
cim:LoadResponseCharacteristic.pFrequencyExponent
//
cim:LoadResponseCharacteristic.qFrequencyExponent
//
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description


#### OperationalLimitSet
cim:IdentifiedObject.name
//
cim:OperationalLimitSet.Terminal 
//
cim:OperationalLimitSet.Equipment 


#### OperationalLimitType
cim:IdentifiedObject.name
//
cim:OperationalLimitType.acceptableDuration
//
cim:OperationalLimitType.direction 
//
entsoe:OperationalLimitType.limitType 
//
cim:IdentifiedObject.description


#### PetersenCoil
cim:IdentifiedObject.name
//
cim:Equipment.EquipmentContainer 
//
cim:IdentifiedObject.description
//
cim:Equipment.aggregate
[red]#Optional? not used inn all objects# 
//


#### PowerTransformer
cim:IdentifiedObject.aliasName
//
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:Equipment.EquipmentContainer 
//
cim:PowerTransformer.isPartOfGeneratorUnit



#### PowerTransformerEnd
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:TransformerEnd.endNumber
//
cim:TransformerEnd.grounded
//
cim:TransformerEnd.BaseVoltage 
//
cim:TransformerEnd.Terminal 
//
cim:PowerTransformerEnd.b0
//
cim:PowerTransformerEnd.b
//
cim:PowerTransformerEnd.connectionKind 
//
cim:PowerTransformerEnd.g
//
cim:PowerTransformerEnd.phaseAngleClock
//
cim:PowerTransformerEnd.r
//
cim:PowerTransformerEnd.r0
//
cim:PowerTransformerEnd.ratedS
//
cim:PowerTransformerEnd.ratedU
//
cim:PowerTransformerEnd.x
//
cim:PowerTransformerEnd.x0
//
cim:PowerTransformerEnd.PowerTransformer 
//


#### RatioTapChanger
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:TapChanger.highStep
//
cim:TapChanger.lowStep
//
cim:TapChanger.ltcFlag
//
cim:TapChanger.neutralStep
//
cim:TapChanger.neutralU
//
cim:TapChanger.normalStep
//
cim:RatioTapChanger.stepVoltageIncrement
//
cim:RatioTapChanger.tculControlMode 
//
cim:RatioTapChanger.TransformerEnd 


#### RegulatingControl
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
//
cim:RegulatingControl.Terminal 
//
cim:RegulatingControl.mode 


#### SubLoadArea
cim:IdentifiedObject.name
//
cim:SubLoadArea.LoadArea 
//
cim:IdentifiedObject.description
//


#### Substation
cim:IdentifiedObject.name
//
cim:Substation.Region 
//
cim:IdentifiedObject.description
//

#### TapChangerControl
cim:IdentifiedObject.description
//
cim:IdentifiedObject.name
//
cim:RegulatingControl.mode 
//
cim:RegulatingControl.Terminal 
//
			

#### Terminal
cim:IdentifiedObject.name
//
cim:IdentifiedObject.description
[red]#Optional? not used inn all objects# 
//
cim:Terminal.ConnectivityNode 
//
cim:Terminal.ConductingEquipment 
//
cim:ACDCTerminal.sequenceNumber
//
cim:Terminal.phases
[red]#Optional? not used inn all objects# 
//


#### VoltageLevel
cim:IdentifiedObject.name
//
cim:VoltageLevel.BaseVoltage 
//
cim:VoltageLevel.Substation 
//
cim:IdentifiedObject.description






